language: c

sudo: false

env:
  - ACLOCAL_PATH=$HOME/share/aclocal

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - autoconf-archive

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then
      curl -fLSs http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2016.03.20.tar.xz | tar xJ &&
      (
        cd autoconf-archive-* &&
        ./configure --prefix="$HOME" &&
        make install;
      );
    fi

script:
  - autoreconf -vi
  - ./configure
  - make

matrix:
  fast_finish: true
