language: c

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: gcc

script:
  - autoreconf
  - ./configure
  - make

matrix:
  fast_finish: true
